# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: juha <juha@student.42seoul.kr>             +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/07/09 15:47:34 by gyim              #+#    #+#              #
#    Updated: 2022/12/20 18:02:05 by juha             ###   ########seoul.kr   #
#                                                                              #
# **************************************************************************** #

NAME = libft.a
CFLAGS = -Wall -Wextra -Werror
RMFLAGS = -f
SRCS =	ft_isalpha.c \
		ft_isdigit.c \
		ft_isalnum.c \
		ft_isascii.c \
		ft_isprint.c \
		ft_strlen.c \
		ft_memset.c \
		ft_bzero.c \
		ft_memcpy.c \
		ft_memmove.c \
		ft_strlcpy.c \
		ft_strlcat.c \
		ft_toupper.c \
        ft_tolower.c \
		ft_strchr.c \
		ft_strrchr.c \
		ft_strncmp.c \
        ft_memchr.c \
        ft_memcmp.c \
        ft_strnstr.c \
		ft_atoi.c \
        ft_calloc.c \
        ft_strdup.c \
        ft_substr.c \
        ft_strjoin.c \
        ft_strtrim.c \
        ft_split.c \
        ft_itoa.c \
        ft_strmapi.c \
        ft_striteri.c \
        ft_putchar_fd.c \
        ft_putstr_fd.c \
		ft_putendl_fd.c \
        ft_putnbr_fd.c
 
BONUS_SRCS=ft_lstnew.c \
			ft_lstadd_front.c \
			ft_lstsize.c \
			ft_lstlast.c \
			ft_lstadd_back.c \
			ft_lstdelone.c \
			ft_lstclear.c \
			ft_lstiter.c \
			ft_lstmap.c

        
OBJS = $(SRCS:.c=.o)
BONUS_OBJS = $(BONUS_SRCS:.c=.o)
ifdef WITH_BONUS
	OBJ = $(OBJS) $(BONUS_OBJS)
else
	OBJ = $(OBJS)
endif

AR = ar
ARFLAGS = rcs

all : $(NAME)

bonus:
	make WITH_BONUS=1 all

$(NAME) :$(OBJ) 
	$(AR) $(ARFLAGS) $@ $^ 

%.o : %.c libft.h
	$(CC) $(CFLAGS) -c $< -I.

clean :
	rm $(RMFLAGS) $(OBJS) $(BONUS_OBJS)

fclean : clean
	rm $(RMFLAGS) $(NAME)

re : 
	make fclean
	make all

.PHONY : all clean fclean re bonus
